// Code generated by protoc-gen-go.
// source: comp.proto
// DO NOT EDIT!

/*
Package comp1 is a generated protocol buffer package.

It is generated from these files:
	comp.proto

It has these top-level messages:
	Request
	ExecuteRequest
	ExecuteResponse
	Component
	Response
*/
package comp1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ExecuteRequest struct {
	Type          string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	ComponentName string `protobuf:"bytes,2,opt,name=componentName" json:"componentName,omitempty"`
}

func (m *ExecuteRequest) Reset()                    { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()               {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExecuteRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ExecuteRequest) GetComponentName() string {
	if m != nil {
		return m.ComponentName
	}
	return ""
}

type ExecuteResponse struct {
}

func (m *ExecuteResponse) Reset()                    { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()               {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Component struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *Component) Reset()                    { *m = Component{} }
func (m *Component) String() string            { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()               {}
func (*Component) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Component) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Component) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Response struct {
	Component []*Component `protobuf:"bytes,1,rep,name=component" json:"component,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Response) GetComponent() []*Component {
	if m != nil {
		return m.Component
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "comp1.Request")
	proto.RegisterType((*ExecuteRequest)(nil), "comp1.ExecuteRequest")
	proto.RegisterType((*ExecuteResponse)(nil), "comp1.ExecuteResponse")
	proto.RegisterType((*Component)(nil), "comp1.Component")
	proto.RegisterType((*Response)(nil), "comp1.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Module service

type ModuleClient interface {
	Fetch(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type moduleClient struct {
	cc *grpc.ClientConn
}

func NewModuleClient(cc *grpc.ClientConn) ModuleClient {
	return &moduleClient{cc}
}

func (c *moduleClient) Fetch(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/comp1.Module/Fetch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := grpc.Invoke(ctx, "/comp1.Module/Execute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Module service

type ModuleServer interface {
	Fetch(context.Context, *Request) (*Response, error)
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
}

func RegisterModuleServer(s *grpc.Server, srv ModuleServer) {
	s.RegisterService(&_Module_serviceDesc, srv)
}

func _Module_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comp1.Module/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServer).Fetch(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Module_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comp1.Module/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Module_serviceDesc = grpc.ServiceDesc{
	ServiceName: "comp1.Module",
	HandlerType: (*ModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _Module_Fetch_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Module_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comp.proto",
}

func init() { proto.RegisterFile("comp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x50, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0x37, 0xd3, 0x6d, 0xe6, 0x89, 0xdb, 0x7c, 0xa0, 0x94, 0x9d, 0x4a, 0xf0, 0x30, 0x3c, 0x04,
	0xb6, 0xdd, 0x76, 0x9c, 0xe8, 0x41, 0x50, 0x4a, 0xbf, 0x81, 0xc6, 0x87, 0x8a, 0x36, 0x89, 0x6d,
	0x0a, 0xfa, 0xed, 0x25, 0x31, 0x4d, 0xe9, 0x6e, 0x2f, 0x2f, 0xbf, 0x7f, 0xef, 0x07, 0xa0, 0x4c,
	0x65, 0xa5, 0xad, 0x8d, 0x33, 0x38, 0xf6, 0xf3, 0x5a, 0x70, 0x98, 0x96, 0xf4, 0xdd, 0x52, 0xe3,
	0xc4, 0x03, 0xcc, 0xee, 0x7e, 0x48, 0xb5, 0x8e, 0xe2, 0x06, 0x11, 0x4e, 0xdc, 0xaf, 0xa5, 0x8c,
	0xe5, 0x6c, 0xc5, 0xcb, 0x30, 0xe3, 0x35, 0x9c, 0x7b, 0xa6, 0xd1, 0xa4, 0xdd, 0xd3, 0x73, 0x45,
	0xd9, 0x28, 0x7c, 0x0e, 0x97, 0xe2, 0x02, 0xe6, 0x49, 0xab, 0xb1, 0x46, 0x37, 0x24, 0xb6, 0xc0,
	0x6f, 0x3b, 0x8c, 0x57, 0xd6, 0x9e, 0x1c, 0x95, 0xfd, 0x9c, 0xdc, 0x46, 0xbd, 0x9b, 0xd8, 0xc1,
	0x69, 0x27, 0x80, 0x12, 0x78, 0x32, 0xc9, 0x58, 0x7e, 0xbc, 0x3a, 0xdb, 0x2c, 0x64, 0xb8, 0x42,
	0x26, 0xe1, 0xb2, 0x87, 0x6c, 0x2c, 0x4c, 0x1e, 0xcd, 0x6b, 0xfb, 0x45, 0x78, 0x03, 0xe3, 0x7b,
	0x72, 0xea, 0x1d, 0x67, 0x11, 0x1f, 0x0f, 0x5c, 0xce, 0xd3, 0x3b, 0x86, 0x3c, 0xc2, 0x1d, 0x4c,
	0x63, 0x72, 0xbc, 0x8c, 0xbf, 0xc3, 0x56, 0x96, 0x57, 0x87, 0xeb, 0x8e, 0xbb, 0xcf, 0x61, 0xf1,
	0x61, 0xe4, 0x5b, 0x6d, 0x95, 0xfc, 0x54, 0xff, 0xa8, 0x3d, 0xf8, 0x6c, 0xeb, 0xc2, 0x77, 0x5e,
	0xb0, 0x97, 0x49, 0x28, 0x7f, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x82, 0x87, 0x33, 0x3b, 0x8a,
	0x01, 0x00, 0x00,
}
